packages:
  - 'packages/*'
  - 'packages/vite-devtools-svelte/client'
  - 'playground'
  - 'examples/*'
  - 'site'

minimumReleaseAgeExclude:
  - '@vitejs/devtools'
  - '@vitejs/devtools-kit'
  - '@vitejs/devtools-rolldown'
  - 'devframe'
